# DATASET CREATION

In [1]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(42)
random.seed(42)

# --- Master data ---
vendors = {
    "V001": "Tata Consultancy Services",
    "V002": "Infosys Ltd",
    "V003": "Wipro Technologies",
    "V004": "HCL Technologies",
    "V005": "Tech Mahindra",
    "V006": "L&T Infotech",
    "V007": "Mphasis",
    "V008": "Hexaware Technologies",
    "V009": "Cognizant India",
    "V010": "Capgemini India",
    "V011": "Amazon Web Services",
    "V012": "Microsoft India",
    "V013": "Oracle India",
    "V014": "SAP India",
    "V015": "IBM India",
    "V016": "Reliance Jio",
    "V017": "Airtel Business",
    "V018": "BSNL",
    "V019": "DHL India",
    "V020": "Blue Dart Express",
}

# Intentionally messy category names (real-world chaos)
categories_messy = [
    "IT Services", "IT services", "IT SERVICES", "it services",
    "Cloud Infrastructure", "Cloud Infra", "cloud infrastructure", "CLOUD",
    "HR & Payroll", "HR Payroll", "HR/Payroll", "Human Resources",
    "Marketing", "marketing", "Mktg", "MARKETING",
    "Logistics", "logistics", "Logistic", "Supply Chain",
    "Legal & Compliance", "Legal", "LEGAL", "legal compliance",
    "Facilities", "facilities", "Facility Management", "FACILITIES",
    "Telecom", "telecom", "Telecommunication", "TELECOM",
]

departments = [
    "Finance", "Operations", "IT", "HR", "Marketing",
    "Legal", "Procurement", "Administration", "Sales", "R&D"
]

payment_methods = ["Bank Transfer", "NEFT", "RTGS", "Cheque", "UPI", "Credit Card", None]

# --- Generate base data ---
n = 600
start_date = datetime(2023, 1, 1)
end_date = datetime(2023, 12, 31)

rows = []
for i in range(n):
    vendor_id = random.choice(list(vendors.keys()))
    vendor_name = vendors[vendor_id]

    # Introduce vendor name inconsistency for some rows
    if random.random() < 0.06:
        vendor_name = vendor_name.upper()
    elif random.random() < 0.04:
        vendor_name = vendor_name.lower()

    category = random.choice(categories_messy)
    department = random.choice(departments)

    # Spend: log-normal to simulate real spend distribution (few large, many small)
    spend = round(np.random.lognormal(mean=10.5, sigma=1.2), 2)

    # Random date
    delta = end_date - start_date
    rand_days = random.randint(0, delta.days)
    date = start_date + timedelta(days=rand_days)

    # Payment method (with NaN)
    payment = random.choice(payment_methods)

    rows.append({
        "vendor_id": vendor_id,
        "vendor_name": vendor_name,
        "category": category,
        "spend_amount": spend,
        "date": date.strftime("%Y-%m-%d"),
        "department": department,
        "payment_method": payment
    })

df = pd.DataFrame(rows)

# --- Inject problems ---

# 1. Missing values: vendor_name, category, spend_amount
for col, pct in [("vendor_name", 0.04), ("category", 0.05), ("spend_amount", 0.03)]:
    mask = np.random.random(len(df)) < pct
    df.loc[mask, col] = np.nan

# 2. Duplicate rows: inject ~30 exact duplicates
dupes = df.sample(30, random_state=7)
df = pd.concat([df, dupes], ignore_index=True)

# 3. Corrupt date format in ~20 rows
bad_date_idx = df.sample(20, random_state=99).index
df.loc[bad_date_idx, "date"] = df.loc[bad_date_idx, "date"].apply(
    lambda d: datetime.strptime(d, "%Y-%m-%d").strftime("%d/%m/%Y") if isinstance(d, str) else d
)

# 4. Negative spend (data entry error)
neg_idx = df.sample(8, random_state=55).index
df.loc[neg_idx, "spend_amount"] = df.loc[neg_idx, "spend_amount"] * -1

# --- Shuffle and save ---
df = df.sample(frac=1, random_state=1).reset_index(drop=True)
df.to_csv("vendor_spend_raw.csv", index=False)

print(f"Dataset generated: {len(df)} rows")
print(f"\nColumn summary:")
print(df.dtypes)
print(f"\nMissing values:")
print(df.isnull().sum())
print(f"\nSample rows:")
print(df.head(10))

Dataset generated: 630 rows

Column summary:
vendor_id          object
vendor_name        object
category           object
spend_amount      float64
date               object
department         object
payment_method     object
dtype: object

Missing values:
vendor_id          0
vendor_name       32
category          31
spend_amount      17
date               0
department         0
payment_method    95
dtype: int64

Sample rows:
  vendor_id            vendor_name          category  spend_amount  \
0      V008  Hexaware Technologies       it services      10459.90
1      V015              IBM India               NaN      44778.95
2      V011    Amazon Web Services             CLOUD      33309.16
3      V002            Infosys Ltd  legal compliance      79846.74
4      V007                    NaN         Logistics      27262.36
5      V008  Hexaware Technologies             LEGAL      26936.65
6      V006           L&T Infotech         MARKETING      44606.82
7      V019              DHL India           TELECOM       6570.22
8      V016           Reliance Jio               NaN     117084.85
9      V003     Wipro Technologies       IT services      24308.92

         date   department payment_method
0  2023-10-22           HR           None
1  11/06/2023           HR  Bank Transfer
2  2023-09-17    Marketing           RTGS
3  2023-02-16           IT           RTGS
4  2023-01-01   Operations  Bank Transfer
5  2023-11-20          R&D         Cheque
6  2023-03-03  Procurement            UPI
7  2023-09-30   Operations           None
8  2023-06-06        Legal           None
9  2023-08-29  Procurement  Bank Transfer

In [2]:
# Fill categorical columns with 'Unknown'
df['vendor_name'].fillna('Unknown', inplace=True)
df['category'].fillna('Unknown', inplace=True)
df['payment_method'].fillna('Unknown', inplace=True)

# Fill numeric column with median (better than mean)
df['spend_amount'].fillna(df['spend_amount'].median(), inplace=True)

C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\2617402255.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['vendor_name'].fillna('Unknown', inplace=True)
C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\2617402255.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category'].fillna('Unknown', inplace=True)
C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\2617402255.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['payment_method'].fillna('Unknown', inplace=True)
C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\2617402255.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['spend_amount'].fillna(df['spend_amount'].median(), inplace=True)

In [3]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [4]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['month_name'] = df['date'].dt.month_name()

In [5]:
print(f"Dataset generated: {len(df)} rows")
print(f"\nColumn summary:")
print(df.dtypes)
print(f"\nMissing values:")
print(df.isnull().sum())
print(f"\nSample rows:")
print(df.head(10))

Dataset generated: 630 rows

Column summary:
vendor_id                 object
vendor_name               object
category                  object
spend_amount             float64
date              datetime64[ns]
department                object
payment_method            object
year                     float64
month                    float64
month_name                object
dtype: object

Missing values:
vendor_id          0
vendor_name        0
category           0
spend_amount       0
date              20
department         0
payment_method     0
year              20
month             20
month_name        20
dtype: int64

Sample rows:
  vendor_id            vendor_name          category  spend_amount       date  \
0      V008  Hexaware Technologies       it services      10459.90 2023-10-22
1      V015              IBM India           Unknown      44778.95        NaT
2      V011    Amazon Web Services             CLOUD      33309.16 2023-09-17
3      V002            Infosys Ltd  legal compliance      79846.74 2023-02-16
4      V007                Unknown         Logistics      27262.36 2023-01-01
5      V008  Hexaware Technologies             LEGAL      26936.65 2023-11-20
6      V006           L&T Infotech         MARKETING      44606.82 2023-03-03
7      V019              DHL India           TELECOM       6570.22 2023-09-30
8      V016           Reliance Jio           Unknown     117084.85 2023-06-06
9      V003     Wipro Technologies       IT services      24308.92 2023-08-29

    department payment_method    year  month month_name
0           HR        Unknown  2023.0   10.0    October
1           HR  Bank Transfer     NaN    NaN        NaN
2    Marketing           RTGS  2023.0    9.0  September
3           IT           RTGS  2023.0    2.0   February
4   Operations  Bank Transfer  2023.0    1.0    January
5          R&D         Cheque  2023.0   11.0   November
6  Procurement            UPI  2023.0    3.0      March
7   Operations        Unknown  2023.0    9.0  September
8        Legal        Unknown  2023.0    6.0       June
9  Procurement  Bank Transfer  2023.0    8.0     August

In [6]:
df['date'].fillna(df['date'].mode()[0], inplace=True)

In [7]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['month_name'] = df['date'].dt.month_name()

In [8]:
df.isnull().sum()

vendor_id         0
vendor_name       0
category          0
spend_amount      0
date              0
department        0
payment_method    0
year              0
month             0
month_name        0
dtype: int64

In [9]:
# Dataset size
len(df)

630

In [10]:
# Column summary
df.dtypes

vendor_id                 object
vendor_name               object
category                  object
spend_amount             float64
date              datetime64[ns]
department                object
payment_method            object
year                       int32
month                      int32
month_name                object
dtype: object

In [11]:
# Missing values
df.isnull().sum()

vendor_id         0
vendor_name       0
category          0
spend_amount      0
date              0
department        0
payment_method    0
year              0
month             0
month_name        0
dtype: int64

In [12]:
# Sample rows
df.head(10)

,vendor_id,vendor_name,category,spend_amount,date,department,payment_method,year,month,month_name
0,V008,Hexaware Technologies,it services,10459.90,2023-10-22,HR,Unknown,2023,10,October
1,V015,IBM India,Unknown,44778.95,2023-06-19,HR,Bank Transfer,2023,6,June
2,V011,Amazon Web Services,CLOUD,33309.16,2023-09-17,Marketing,RTGS,2023,9,September
3,V002,Infosys Ltd,legal compliance,79846.74,2023-02-16,IT,RTGS,2023,2,February
4,V007,Unknown,Logistics,27262.36,2023-01-01,Operations,Bank Transfer,2023,1,January
5,V008,Hexaware Technologies,LEGAL,26936.65,2023-11-20,R&D,Cheque,2023,11,November
6,V006,L&T Infotech,MARKETING,44606.82,2023-03-03,Procurement,UPI,2023,3,March
7,V019,DHL India,TELECOM,6570.22,2023-09-30,Operations,Unknown,2023,9,September
8,V016,Reliance Jio,Unknown,117084.85,2023-06-06,Legal,Unknown,2023,6,June
9,V003,Wipro Technologies,IT services,24308.92,2023-08-29,Procurement,Bank Transfer,2023,8,August

In [13]:
df['category'] = df['category'].str.lower()
df['category'].fillna('unknown', inplace=True)

C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\779043322.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category'].fillna('unknown', inplace=True)

In [14]:
import pandas as pd
import numpy as np

# load dataset
df = pd.read_csv("vendor_spend_raw.csv")

# check shape (rows, columns)
df.shape


# ── 1. REMOVE DUPLICATES ──
# remove repeated rows to avoid double counting
df = df.drop_duplicates()

# check data
df.head(10)


# ── 2. FIX DATE FORMAT ──
# convert date column into proper datetime format
# errors='coerce' will convert wrong values into NaT
df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')

# remove rows where date is missing (NaT)
df = df.dropna(subset=['date'])


# ── 3. HANDLE NEGATIVE SPEND ──
# find rows where spend is negative
neg_mask = df['spend_amount'] < 0

# create new column to mark transaction type
# if negative → Credit Note, else → Invoice
df['transaction_type'] = np.where(neg_mask, 'Credit Note', 'Invoice')

# convert all spend values to positive
df['spend_amount'] = df['spend_amount'].abs()


# ── 4. HANDLE MISSING SPEND ──
# fill missing spend values using median
df['spend_amount'] = df['spend_amount'].fillna(df['spend_amount'].median())


# ── 5. STANDARDIZE CATEGORY ──
# convert to lowercase and remove extra spaces
df['category'] = df['category'].str.strip().str.lower()

# fill missing values
df['category'] = df['category'].fillna('unknown')

# map different names into one standard name
category_map = {
    'it services': 'IT Services',
    'it service': 'IT Services',
    'it services': 'IT Services',       # catches uppercase version after lower()
    'cloud': 'Cloud Infrastructure',
    'cloud infra': 'Cloud Infrastructure',
    'cloud infrastructure': 'Cloud Infrastructure',
    'hr payroll': 'HR & Payroll',
    'hr/payroll': 'HR & Payroll',
    'hr & payroll': 'HR & Payroll',
    'human resources': 'HR & Payroll',
    'marketing': 'Marketing',           # you missed this
    'mktg': 'Marketing',
    'logistics': 'Logistics',           # you missed this
    'logistic': 'Logistics',
    'supply chain': 'Logistics',
    'legal': 'Legal & Compliance',
    'legal compliance': 'Legal & Compliance',
    'legal & compliance': 'Legal & Compliance',
    'facilities': 'Facilities',         # you missed this entirely
    'facility management': 'Facilities',
    'telecom': 'Telecom',               # you missed this
    'telecommunication': 'Telecom',
    'unknown': 'Unknown',
}

# replace values using mapping
df['category'] = df['category'].map(category_map).fillna('Unknown')

# check categories
df['category'].value_counts()


# ── 6. HANDLE MISSING VENDOR NAME ──
# create reference from existing vendor_id → vendor_name
vendor_map = df.dropna(subset=['vendor_name']) \
               .drop_duplicates('vendor_id') \
               .set_index('vendor_id')['vendor_name']

# fill missing vendor names using vendor_id
df['vendor_name'] = df.apply(
    lambda row: vendor_map.get(row['vendor_id'], 'Unknown')
    if pd.isna(row['vendor_name']) else row['vendor_name'],
    axis=1
)


# ── 7. HANDLE PAYMENT METHOD ──
# fill missing values
df['payment_method'] = df['payment_method'].fillna('Unknown')


# ── 8. CREATE DATE FEATURES ──
# extract year, month, month name, quarter
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['month_name'] = df['date'].dt.month_name()
df['quarter'] = df['date'].dt.quarter

# create quarter label like Q1, Q2
df['quarter_label'] = 'Q' + df['quarter'].astype(str)


# ── 9. CREATE SPEND CATEGORY (TIER) ──
# divide spend into groups based on amount
df['spend_tier'] = pd.cut(
    df['spend_amount'],
    bins=[0, 10000, 50000, 200000, float('inf')],
    labels=['Tail (<₹10K)', 'Mid (₹10K–50K)', 'Strategic (₹50K–2L)', 'Critical (>₹2L)']
)

# check result
df['spend_tier'].value_counts()


# ── 10. FINAL CHECK ──
# check missing values
df.isnull().sum()

# check data types
df.dtypes

# preview data
df.head(10)


# save cleaned dataset
df.to_csv("vendor_spend_clean.csv", index=False)

C:\Users\mahaj\AppData\Local\Temp\ipykernel_21496\3190856865.py:22: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')

In [15]:
df.isnull().sum()

vendor_id           0
vendor_name         0
category            0
spend_amount        0
date                0
department          0
payment_method      0
transaction_type    0
year                0
month               0
month_name          0
quarter             0
quarter_label       0
spend_tier          0
dtype: int64

In [16]:
df.dtypes

vendor_id                   object
vendor_name                 object
category                    object
spend_amount               float64
date                datetime64[ns]
department                  object
payment_method              object
transaction_type            object
year                         int32
month                        int32
month_name                  object
quarter                      int32
quarter_label               object
spend_tier                category
dtype: object

In [17]:
df.head(10)

,vendor_id,vendor_name,category,spend_amount,date,department,payment_method,transaction_type,year,month,month_name,quarter,quarter_label,spend_tier
0,V008,Hexaware Technologies,IT Services,10459.90,2023-10-22,HR,Unknown,Invoice,2023,10,October,4,Q4,Mid (₹10K–50K)
2,V011,Amazon Web Services,Cloud Infrastructure,33309.16,2023-09-17,Marketing,RTGS,Invoice,2023,9,September,3,Q3,Mid (₹10K–50K)
3,V002,Infosys Ltd,Legal & Compliance,79846.74,2023-02-16,IT,RTGS,Invoice,2023,2,February,1,Q1,Strategic (₹50K–2L)
4,V007,Mphasis,Logistics,27262.36,2023-01-01,Operations,Bank Transfer,Invoice,2023,1,January,1,Q1,Mid (₹10K–50K)
5,V008,Hexaware Technologies,Legal & Compliance,26936.65,2023-11-20,R&D,Cheque,Invoice,2023,11,November,4,Q4,Mid (₹10K–50K)
6,V006,L&T Infotech,Marketing,44606.82,2023-03-03,Procurement,UPI,Invoice,2023,3,March,1,Q1,Mid (₹10K–50K)
7,V019,DHL India,Telecom,6570.22,2023-09-30,Operations,Unknown,Invoice,2023,9,September,3,Q3,Tail (<₹10K)
8,V016,Reliance Jio,Unknown,117084.85,2023-06-06,Legal,Unknown,Invoice,2023,6,June,2,Q2,Strategic (₹50K–2L)
9,V003,Wipro Technologies,IT Services,24308.92,2023-08-29,Procurement,Bank Transfer,Invoice,2023,8,August,3,Q3,Mid (₹10K–50K)
10,V011,Amazon Web Services,Marketing,8222.43,2023-09-13,IT,UPI,Invoice,2023,9,September,3,Q3,Tail (<₹10K)

In [18]:
import subprocess
subprocess.run(['pip', 'install', 'psycopg2-binary'], check=True)

CompletedProcess(args=['pip', 'install', 'psycopg2-binary'], returncode=0)

In [19]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:Root@localhost:5432/vendor_db')

try:
    with engine.connect() as conn:
        print("Connection successful")
except Exception as e:
    print(f"Failed: {e}")

Connection successful

In [20]:
df.to_sql('vendor_spend', engine, if_exists='replace', index=False)
print("Data loaded successfully. Rows loaded:", len(df))

Data loaded successfully. Rows loaded: 582

In [1]:
import os
print(os.getcwd())

C:\Users\mahaj\Portfolio\Vendor Spend Intelligence & Cost Optimization System — India B2B Procurement Analysis

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("vendor_spend_clean.csv")

print("=" * 55)
print("   VENDOR SPEND COST REDUCTION SIMULATION")
print("=" * 55)

total_spend = df['spend_amount'].sum()
print(f"\nBaseline Total Spend: ₹{total_spend:,.2f}")

# ── SCENARIO 1: Renegotiate top 3 vendors by 10% ──
top3 = df.groupby('vendor_name')['spend_amount'].sum().nlargest(3)
top3_spend = top3.sum()
scenario1_saving = top3_spend * 0.10
print(f"\n SCENARIO 1: Renegotiate Top 3 Vendors by 10%")
print(f"  Top 3 Vendor Spend : ₹{top3_spend:,.2f}")
print(f"  Projected Saving   : ₹{scenario1_saving:,.2f}")
print(f"  New Total Spend    : ₹{(total_spend - scenario1_saving):,.2f}")

# ── SCENARIO 2: Reduce Cloud Infrastructure by 15% ──
cloud_spend = df[df['category'] == 'Cloud Infrastructure']['spend_amount'].sum()
scenario2_saving = cloud_spend * 0.15
print(f"\n SCENARIO 2: Reduce Cloud Infrastructure Spend by 15%")
print(f"  Cloud Spend        : ₹{cloud_spend:,.2f}")
print(f"  Projected Saving   : ₹{scenario2_saving:,.2f}")
print(f"  New Total Spend    : ₹{(total_spend - scenario2_saving):,.2f}")

# ── SCENARIO 3: Cap Sales dept transactions above ₹1L ──
sales_high = df[
    (df['department'] == 'Sales') & 
    (df['spend_amount'] > 100000)
]['spend_amount'].sum()
scenario3_saving = sales_high * 0.12
print(f"\n SCENARIO 3: 12% Control on Sales Transactions Above ₹1L")
print(f"  High-Value Sales   : ₹{sales_high:,.2f}")
print(f"  Projected Saving   : ₹{scenario3_saving:,.2f}")
print(f"  New Total Spend    : ₹{(total_spend - scenario3_saving):,.2f}")

# ── COMBINED IMPACT ──
total_saving = scenario1_saving + scenario2_saving + scenario3_saving
print(f"\n{'=' * 55}")
print(f" COMBINED SAVING ACROSS ALL 3 SCENARIOS")
print(f"  Total Projected Saving : ₹{total_saving:,.2f}")
print(f"  New Total Spend        : ₹{(total_spend - total_saving):,.2f}")
print(f"  Cost Reduction %       : {(total_saving/total_spend*100):.2f}%")
print(f"{'=' * 55}")

=======================================================
   VENDOR SPEND COST REDUCTION SIMULATION
=======================================================

Baseline Total Spend: ₹41,541,008.67

 SCENARIO 1: Renegotiate Top 3 Vendors by 10%
  Top 3 Vendor Spend : ₹11,740,298.72
  Projected Saving   : ₹1,174,029.87
  New Total Spend    : ₹40,366,978.80

 SCENARIO 2: Reduce Cloud Infrastructure Spend by 15%
  Cloud Spend        : ₹8,954,266.96
  Projected Saving   : ₹1,343,140.04
  New Total Spend    : ₹40,197,868.63

 SCENARIO 3: 12% Control on Sales Transactions Above ₹1L
  High-Value Sales   : ₹6,081,030.11
  Projected Saving   : ₹729,723.61
  New Total Spend    : ₹40,811,285.06

=======================================================
 COMBINED SAVING ACROSS ALL 3 SCENARIOS
  Total Projected Saving : ₹3,246,893.53
  New Total Spend        : ₹38,294,115.14
  Cost Reduction %       : 7.82%
=======================================================